---
# Source: generic-backend-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: user-v1-secret
type: Opaque
data:
  DATABASE_PASSWORD: "ZHVtbXktcGFzc3dvcmQ="
  KEY_VAULT_CLIENT_SECRET: "ZHVtbXktY2xpZW50LXNlY3JldA=="
---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-v1-config-map
data:
    JAVA_OPTS: "-Xms256M -Xmx256M"
    SQL_SERVER_DOMAIN: "sqleu2dummy01.database.windows.net"
    DATABASE_NAME: "identity"
    DATABASE_USER: "user-dummy01"
    KEY_VAULT_SERVER_DOMAIN: "kveu2dummy01.vault.azure.net"
    KEY_VAULT_CLIENT_ID: "dummy-client-id"
---
# Source: generic-backend-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-v1
  labels:
    app: user-v1
spec:
  type: NodePort
  selector:
    app: user-v1
  ipFamilies:
    - IPv4
  ports:
    - name: user-v1
      port: 8080
      nodePort: 30080
---
# Source: generic-backend-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-v1
  labels:
    app: user-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-v1
  template:
    metadata:
      labels:
        app: user-v1
    spec:
      containers:
        - name: user-v1
          image: "miguelarmasabt/money-exchange:v1.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30

          env:
              - name: JAVA_OPTS
                valueFrom:
                  configMapKeyRef:
                    name: user-v1-config-map
                    key: JAVA_OPTS

              - name: SQL_SERVER_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: user-v1-config-map
                    key: SQL_SERVER_DOMAIN

              - name: DATABASE_NAME
                valueFrom:
                  configMapKeyRef:
                    name: user-v1-config-map
                    key: DATABASE_NAME

              - name: DATABASE_USER
                valueFrom:
                  configMapKeyRef:
                    name: user-v1-config-map
                    key: DATABASE_USER

              - name: KEY_VAULT_SERVER_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: user-v1-config-map
                    key: KEY_VAULT_SERVER_DOMAIN

              - name: KEY_VAULT_CLIENT_ID
                valueFrom:
                  configMapKeyRef:
                    name: user-v1-config-map
                    key: KEY_VAULT_CLIENT_ID

              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: user-v1-secret
                    key: DATABASE_PASSWORD

              - name: KEY_VAULT_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: user-v1-secret
                    key: KEY_VAULT_CLIENT_SECRET
